variable "env" {}
variable "project_id" {}
variable "project_name" {}
variable "project_number" {}
variable "region" {}
variable "data_platform_ops_br" {}
variable "display_name" {}
variable "description" {}
variable "type" {}
variable "region_dr" {}