env = "pr"
project_id = "divine-energy-253221"
project_name = "My Project 96351"
project_number = "76231282453"
region = "northamerica-northeast1"
data_platform_ops_br = "main"

display_name = "test display name"
description = "test description"
type = "email"
region_dr = "northamerica-northeast2"