steps:
- id: 'terraform plan' 
  name: 'hashicorp/terraform:1.0.0'
  dir: ./terraform
  entrypoint: sh
  args:
  - '-c'
  - |
    terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}" -backend-config="${BACKEND_CONFIG_PREFIX}"
    terraform apply -auto-approve
substitutions: 
  _BACKEND_CONFIG_BUCKET: bucket=${PROJECT_ID}-tfstate
  _BACKEND_CONFIG_PREFIX: state
