steps:
- id: 'terraform plan' 
  name: 'hashicorp/terraform:1.0.0'
  dir: ./terraform
  entrypoint: sh
  args:
  - '-c'
  - |
    terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}"
    terraform apply -var-file=tfvars/pr.tfvars -auto-approve
substitutions: 
  _BACKEND_CONFIG_BUCKET: bucket=${PROJECT_ID}-tfstate
  
