steps:
- id: 'terraform plan' 
  name: 'hashicorp/terraform:1.4.6'
  dir: ./terraform
  entrypoint: sh
  args:
  - '-c'
  - |
    terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}"
    terraform plan -var-file="${_VAR_FILE}""
substitutions: 
  _BACKEND_CONFIG_BUCKET: bucket=${PROJECT_ID}-tfstate
  _BACKEND_CONFIG_PREFIX: prefix=terraform/np
  _VAR_FILE: ../tfvars/pr.tfvars
  _TF_COMMAND: plan
  _DIR: "."
  _TF_DIR: terraform
