steps:
- id: 'terraform plan' 
  name: 'hashicorp/terraform:1.4.6'
  dir: ./terraform
  entrypoint: sh
  args:
  - '-c'
  - |
    terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}"
    terraform plan -var-file=${path.module}/tfvars/pr.tfvars
substitutions: 
  _BACKEND_CONFIG_BUCKET: bucket=${PROJECT_ID}-tfstate 
